# Basic settings for running in production. Change accordingly before deploying the server.

# Enabled features
features=declarative-ui,account-api,token-exchange,admin-fine-grained-authz,preview,authorization-js-policy

# Database

# The database vendor.
db=postgres

# The username of the database user.
#db-username=keycloak

# The password of the database user.
#db-password=password

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
#db-url=jdbc:postgresql://localhost/keycloak

# Observability
# If the server should expose healthcheck endpoints.
health-enabled=true
# If the server should expose metrics endpoints.
metrics-enabled=true

log=console,file
# Log asynchonously to improve performance
log-async=true
# Use Elastic Common Schema (ECS) format for log file output - ideally it'll get forwarded to Application Insights
log-file-output=json
log-file-json-format=ecs
log-console-output=json
log-console-json-format=ecs
# Connection pool size for the database
connection-pool-size=5
# Enable backchannel requests to use dynamic hostnames (useful for clustered environments)
hostname-backchannel-dynamic=true
# If we hit 512 queued requests a second instance should be on it's way up...
http-max-queued-requests=512
# The file path to a server certificate or certificate chain in PEM format.
# Lives in the truststores directory so that we trust our own cert.
https-certificate-file=${kc.home.dir}/conf/truststores/server.crt.pem
# The file path to a private key in PEM format.
https-certificate-key-file=${kc.home.dir}/conf/server.key.pem
# The proxy address forwarding mode if the server is behind a reverse proxy.
proxy-headers=xforwarded
# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
spi-sticky-session-encoder-infinispan-should-attach-route=false
