POST https://login.jollybush-836e15bc.westus3.azurecontainerapps.io/realms/compliance-theatre/protocol/openid-connect/token
content-type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=${{CLIENT_ID}}&client_secret=${{CLIENT_SECRET}}

